name: The Realm of Aurii
url: http://aurii.us
baseurl: 
title: The Realm of Aurii
description: Gaming blog run by William R Clark

theme: jekyll-theme-midnight
show_downloads: false

collections:
  aurii_library:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: aurii

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-109921332-2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
